# In this assignment students will build the random forest model after
normalizing the variable to house pricing from boston data set.


In [111]:
#Following the code to get data into the environment:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler 
from sklearn import datasets 
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score


In [112]:
boston = datasets.load_boston()
features = pd.DataFrame(boston.data,columns=boston.feature_names)
targets = boston.target

In [113]:
features.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [114]:
scaler = StandardScaler()

In [115]:
#scaler.fit_transform(features)

In [116]:
X = features
y = boston.target

In [117]:
X.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
dtype: int64

In [118]:
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size = 0.2, random_state = 2)

In [119]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(404, 13)
(404,)
(102, 13)
(102,)


In [120]:
y_train[:40]

array([23.1, 21. , 20.1, 34.7, 13.9, 13.5, 22. , 15.2, 10.9, 22.7, 13.8,
        5.6, 29.8, 50. , 34.9, 20.6, 23.4, 19.2, 32.7, 19.6, 27. ,  8.4,
       46. , 21.7, 27.1, 19.4, 19.3, 24.8, 22.6, 31.7, 18.5,  8.7, 17.4,
       23.7, 13.3, 10.5, 12.7, 25. , 19.7, 14.9])

In [121]:
y_test[:40]

array([20.2, 15.3, 37.3, 32.5,  8.8, 14.4, 22. , 26.6, 15. , 21.5, 29.4,
       24.8, 22. , 16.1, 13.9, 21.6, 21.7, 12.8,  7.2, 12.6, 20.7, 19.3,
       36.5, 17.7, 16.7, 20.2, 50. , 34.6, 35.4, 19.4, 20.8, 21.1, 31.1,
       23.5,  8.3, 15.6, 11.3, 21.7, 23.2, 20.8])

In [122]:
rtc = RandomForestRegressor(n_estimators= 100, random_state= 1)

In [123]:
rtc.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=100,
                      n_jobs=None, oob_score=False, random_state=1, verbose=0,
                      warm_start=False)

In [124]:
print("Variance Score : {}".format(rtc.score(X_test,y_test)))

Variance Score : 0.892814118972812


In [129]:
y_pred = rtc.predict(X_test)

In [130]:
y_test[:40]

array([20.2, 15.3, 37.3, 32.5,  8.8, 14.4, 22. , 26.6, 15. , 21.5, 29.4,
       24.8, 22. , 16.1, 13.9, 21.6, 21.7, 12.8,  7.2, 12.6, 20.7, 19.3,
       36.5, 17.7, 16.7, 20.2, 50. , 34.6, 35.4, 19.4, 20.8, 21.1, 31.1,
       23.5,  8.3, 15.6, 11.3, 21.7, 23.2, 20.8])

In [131]:
y_pred[:40]

array([21.368, 21.405, 32.28 , 30.449,  8.484, 13.596, 26.389, 28.029,
       28.738, 21.139, 26.504, 24.793, 20.223, 20.467, 11.372, 22.17 ,
       17.856, 11.137,  8.791, 15.573, 23.481, 19.984, 35.486, 18.459,
       14.088, 19.275, 42.895, 32.704, 34.236, 20.177, 20.228, 20.732,
       30.709, 25.612, 11.749, 16.661, 10.854, 21.137, 22.181, 21.373])

In [137]:
pred_score = round(rtc.score(X_test, y_test), 2)

In [145]:
print("Pred Score is {:.2f}%".format(pred_score * 100))

Pred Score is 89.00%
